runtime: python38  # or another supported version

entrypoint: streamlit run app.py --server.port $PORT --server.headless true --server.address 0.0.0.0

automatic_scaling:
  min_idle_instances: automatic  # default is automatic

env_variables:
  # Environment variables you want to pass into your application
